export const goneUrls = [
  "/testimonials/mortgage-choice/",
  "/testimonials/artisan-ornaments/",
  "/testimonials/containerspace/",
  "/testimonials/smartcool-systems-australia/",
  "/testimonials/algra-enterprises-trading-as-groovy-glass/",
  "/testimonials/australian-surface-treatments/",
  "/testimonials/coates-hire-operations-pty-ltd/",
  "/testimonials/eps-environmental-property-services/",
  "/testimonials/bresnehan-company-2/",
  "/testimonials/herron-todd-white/",
  "/testimonials/link-strata-management/",
  "/testimonials/electrical-estimating-solutions/",
  "/testimonials/burpengary-state-secondary-college/",
  "/testimonials/private-wealth-partners-group-pty-ltd/",
  "/testimonials/tla-australia-ltd/",
  "/testimonials/persal-and-co/",
  "/testimonials/bekaert/",
  "/testimonials/cindy-geer/",
  "/testimonials/east-global-finance/",
  "/testimonials/mayers-fine-food/",
  "/testimonials/parkstone-hr/",
  "/testimonials/east-global-finance/attachment/east_global_finance/",
  "/testimonials/east-global-finance/attachment/marys_house_services/",
  "/testimonials/rook-sheu/attachment/rook-partners_rook-sheu-ptd-ltd_logo/",
  "/testimonials/traffic-act/",
  "/testimonials/gymnastics-australia/",
  "/testimonials/traffic-act-2/",
  "/testimonials/bronze-snake-pty-ltd/",
  "/testimonials/fitzpatricks-squash-inc/",
  "/testimonials/warringtonfire-australia-pty-ltd/",
  "/microsoft-excel/attachment/dashboard_pie-chart_bar-graph_reporting-solutions_microsoft-excel-experts/",
  "/testimonials/environmental-monitoring-services/",
  "/microsoft-excel/attachment/microsoft-powerapps_microsoft-excel-experts/",
  "/testimonials/holistic-athlete-development/",
  "/microsoft-excel/attachment/upgrade-microsoft-excel_microsoft-excel-experts/",
  "/upgrades-and-migration/attachment/data-migration-2/",
  "/microsoft-excel/attachment/support-icon/",
].map((url) => url.toLowerCase());

export const moreGoneUrls = [
  "/government-departments",
  "/companies-and-organisations",
  "/popup-forms",
  "/upgrades-and-migration/attachment/cloud-migration-2",
  "/training",
  "/author/ppexperts",
  "/remove-repetition-and-increase-productivity",
  "/microsoft-excel/attachment/microsoft-access-consulting-services_access-experts",
  "/custom-toolbars-and-ribbons",
  "/corporate-identity",
  "/word-document-template-creation",
  "/quick-parts",
  "/word-template-conversions",
  "/accessibility",
  "/tips-and-tricks/printing-adding-the-full-saved-file-path-to-headers-and-footers-in-excel-2002",
  "/tips-and-tricks/general-show-all-menu-items-automatically-in-excel",
  "/tips-and-tricks/general-automatically-creating-charts-in-excel",
  "/fusion_tb_category/header",
  "/excel-consulting-services",
  "/fusion_tb_category/footer",
  "/excel-consultants",
  "/tips-and-tricks",
  "/tips-and-tricks/feed",
  "/portfolio",
  "/free-macros",
  "/testimonials/the-money-institute",
  "/author/grant",
  "/faq",
  "/testimonials/essential-property-solutions",
  "/corporate-global-template-solution",
].map((url) => url.toLowerCase());

// Combined array for easier use
export const allGoneUrls = [...goneUrls, ...moreGoneUrls];
