export const FormsSvg = () => {
  return (
    <svg viewBox="0 0 48 48" fill="none" aria-hidden="true">
      <rect
        x="4"
        y="8"
        width="40"
        height="32"
        rx="4"
        stroke="currentColor"
        strokeWidth="1.8"
      />
      <rect
        x="10"
        y="16"
        width="16"
        height="6"
        rx="2"
        stroke="currentColor"
        strokeWidth="1.5"
        opacity="0.7"
      />
      <rect
        x="10"
        y="26"
        width="10"
        height="6"
        rx="2"
        stroke="currentColor"
        strokeWidth="1.5"
        opacity="0.7"
      />
      <rect
        x="30"
        y="26"
        width="8"
        height="6"
        rx="2"
        fill="currentColor"
        opacity="0.9"
      />
      <line
        x1="29"
        y1="16"
        x2="38"
        y2="16"
        stroke="currentColor"
        strokeWidth="1.5"
        opacity="0.4"
      />
      <line
        x1="29"
        y1="20"
        x2="35"
        y2="20"
        stroke="currentColor"
        strokeWidth="1.5"
        opacity="0.4"
      />
    </svg>
  );
};
