export const RibbonSvg = () => {
  return (
    <svg viewBox="0 0 48 48" fill="none" aria-hidden="true">
      <rect
        x="4"
        y="10"
        width="40"
        height="10"
        rx="3"
        stroke="currentColor"
        strokeWidth="1.8"
      />
      <rect
        x="8"
        y="13"
        width="6"
        height="4"
        rx="1.5"
        fill="currentColor"
        opacity="0.8"
      />
      <rect
        x="17"
        y="13"
        width="6"
        height="4"
        rx="1.5"
        stroke="currentColor"
        strokeWidth="1.4"
        opacity="0.6"
      />
      <rect
        x="26"
        y="13"
        width="6"
        height="4"
        rx="1.5"
        stroke="currentColor"
        strokeWidth="1.4"
        opacity="0.6"
      />
      <rect
        x="35"
        y="13"
        width="5"
        height="4"
        rx="1.5"
        stroke="currentColor"
        strokeWidth="1.4"
        opacity="0.6"
      />
      <rect
        x="4"
        y="24"
        width="40"
        height="16"
        rx="3"
        stroke="currentColor"
        strokeWidth="1.5"
        opacity="0.35"
      />
      <line
        x1="4"
        y1="20"
        x2="44"
        y2="20"
        stroke="currentColor"
        strokeWidth="1"
        opacity="0.25"
      />
    </svg>
  );
};
